from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

Attributes = dict[str, Any]


class SpanLike(Protocol):
    def end(self) -> None: ...
    def add_event(self, name: str, attrs: Attributes | None = None) -> None: ...
    def set_attribute(self, key: str, value: Any) -> None: ...
    def record_exception(self, err: BaseException) -> None: ...


class Telemetry(Protocol):
    def init(self) -> None: ...
    def shutdown(self) -> None: ...
    def event(self, name: str, attrs: Attributes | None = None) -> None: ...
    def start_span(self, name: str, attrs: Attributes | None = None) -> SpanLike: ...
    def with_span(self, name: str, fn: Callable[[SpanLike], Any], attrs: Attributes | None = None) -> Any: ...
    def set_user(self, user: dict[str, Any] | None = None) -> None: ...
    def set_attributes(self, attrs: Attributes) -> None: ...
    def record_exception(self, err: BaseException, attrs: Attributes | None = None) -> None: ...
